# Generated by Django 3.0.5 on 2020-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sha256_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
