# Generated by Django 3.0.5 on 2020-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_sha256_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='veri_type',
            field=models.CharField(default='register', max_length=32),
            preserve_default=False,
        ),
    ]
