# Generated by Django 3.0.5 on 2020-06-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='favor',
            options={'verbose_name': '点赞记录', 'verbose_name_plural': '点赞记录'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
    ]
