# Generated by Django 3.0.5 on 2020-04-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
