# Generated by Django 3.0.5 on 2020-05-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200517_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favor',
            old_name='publisher',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorcnt',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
