# Generated by Django 3.0.5 on 2020-06-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='self_favor',
        ),
    ]
