# Generated by Django 3.0.5 on 2020-05-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200413_0921'),
        ('post', '0004_auto_20200517_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favor',
            unique_together={('post', 'user')},
        ),
    ]
